version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - VITE_API_URL=http://backend:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    environment:
      - NODE_ENV=development

networks:
  default:
    driver: bridge
